# $Id: Makefile.label,v 1.2.2.6 2006/05/05 09:54:28 dumb Exp $

.PHONY: label

SHELL := /bin/bash

include project.conf
include .make/Makefile.defs

define label_inc
bash -c "`sed 's/\(\([0-9]*_\)\{3\}\)\([0-9]*\)\(.*\)/A=\1 ; B=$$(( \3 + 1 )) ; C=\4 ; echo $$A$$B$$C/' <version`" >version
endef

define label_cvs
${get_label} ; \
cd .. && ${CVS} commit -m "Release $$LABEL" && ${CVS} tag $$LABEL
endef

label-inc:
	@${label_inc}

label: label-inc
	@${label_cvs}
