package talkie.server.dispatchers.corba;


/**
* talkie/server/dispatchers/corba/IDLTalkieServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 16:25:32 MSK
*/

public interface IDLTalkieServerOperations 
{
  boolean login (String login, String pass);
  void logout (String login);
  void postMessage (String login, String message);
  void whoIsHere (String login);
} // interface IDLTalkieServerOperations
