package talkie.server.dispatchers.corba;


/**
* talkie/server/dispatchers/corba/IDLTalkieServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 16:25:32 MSK
*/

public interface IDLTalkieServer extends IDLTalkieServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDLTalkieServer
