module corba {
    interface IDLTalkieClient {
        string getLogin();
        string getPass();
        void deliverMessage(in string message);
    };

    interface IDLTalkieServer {
        boolean login(in IDLTalkieClient client);
        void logout(in string login);
        void postMessage(in string login, in string message);
        void whoIsHere(in string login);
    };
};