module corba {
    interface IDLTalkieClient {
        wstring getLogin();
        wstring getPass();
        void deliverMessage(in wstring message);
    };

    interface IDLTalkieServer {
        boolean login(in IDLTalkieClient client);
        void logout(in wstring login);
        void postMessage(in wstring login, in wstring message);
        void whoIsHere(in wstring login);
    };
};