# $Id: Makefile.static,v 1.3.4.3 2007/09/11 14:13:10 dumb Exp $

test-header-inc/%:
	@echo '#include <$*>' > ${OBJDIR}/static-test-$*.cpp
	@${CXX} -c -o ${OBJDIR}/static-test-$*.o ${defs} ${incs} ${cppflags} ${cxxflags} ${OBJDIR}/static-test-$*.cpp
	@rm -f ${OBJDIR}/static-test-$*.{cpp,o}

test-header: $(addprefix test-header-,$(wildcard inc/*.h))

#test-header:
#	@[ ! -d ./inc ] || find ./inc -name '*.h' -exec ${CXX} -c -o /dev/null -x c++ ${defs} ${incs} ${cppflags} ${cxxflags} \{} \;
