package talkie.common.corba;

/**
* talkie/common/corba/IDLTalkieServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 19:08:26 MSK
*/

public final class IDLTalkieServerHolder implements org.omg.CORBA.portable.Streamable
{
  public talkie.common.corba.IDLTalkieServer value = null;

  public IDLTalkieServerHolder ()
  {
  }

  public IDLTalkieServerHolder (talkie.common.corba.IDLTalkieServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = talkie.common.corba.IDLTalkieServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    talkie.common.corba.IDLTalkieServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return talkie.common.corba.IDLTalkieServerHelper.type ();
  }

}
