package ru.spb.etu.auto;

/** Class _Painting was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Painting extends org.apache.cayenne.CayenneDataObject {

    public static final String TITLE_PROPERTY = "title";
    public static final String ARTIST_PROPERTY = "artist";
    public static final String GALLERY_PROPERTY = "gallery";

    public static final String ID_PK_COLUMN = "ID";

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setArtist(ru.spb.etu.Artist artist) {
        setToOneTarget("artist", artist, true);
    }

    public ru.spb.etu.Artist getArtist() {
        return (ru.spb.etu.Artist)readProperty("artist");
    } 
    
    
    public void setGallery(ru.spb.etu.Gallery gallery) {
        setToOneTarget("gallery", gallery, true);
    }

    public ru.spb.etu.Gallery getGallery() {
        return (ru.spb.etu.Gallery)readProperty("gallery");
    } 
    
    
}
