CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		eav_lab_1.o

LIBS =

TARGET =	eav_lab_1.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
