DROP TABLE IF EXISTS etu.db_sculpture CASCADE
;

DROP TABLE IF EXISTS etu.db_painting CASCADE
;

DROP TABLE IF EXISTS etu.db_masterpiece CASCADE
;

DROP TABLE IF EXISTS etu.db_genre CASCADE
;

DROP TABLE IF EXISTS etu.db_artist CASCADE
;

DROP TABLE IF EXISTS etu.db_museum CASCADE
;

CREATE TABLE etu.db_museum (ID INT NOT NULL, description VARCHAR(255) NULL, imageURL VARCHAR(255) NULL, name VARCHAR(50) NULL, www VARCHAR(255) NULL, PRIMARY KEY (ID))
;

CREATE TABLE etu.db_artist (ID INT NOT NULL, birthdate DATETIME NULL, country VARCHAR(10) NULL, description VARCHAR(255) NULL, imageUrl VARCHAR(255) NULL, name VARCHAR(30) NULL, PRIMARY KEY (ID))
;

CREATE TABLE etu.db_genre (ID INT NOT NULL, Name VARCHAR(255) NULL, descrption VARCHAR(255) NULL, imageURL VARCHAR(255) NULL, PRIMARY KEY (ID))
;

CREATE TABLE etu.db_masterpiece (ID INT NOT NULL, ID_artist INT NOT NULL, ID_genre INT NOT NULL, ID_museum INT NULL, ID_type INT NOT NULL, creationYear INT NULL, description VARCHAR(255) NULL, imageURL VARCHAR(255) NULL, photo VARCHAR(255) NULL, title VARCHAR(255) NULL, PRIMARY KEY (ID))
;

CREATE TABLE etu.db_painting (ID INT NOT NULL, height INT NULL, width INT NULL, PRIMARY KEY (ID))
;

CREATE TABLE etu.db_sculpture (ID INT NOT NULL, mass INT NULL, material VARCHAR(40) NULL, PRIMARY KEY (ID))
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID INTEGER NOT NULL, UNIQUE (TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('db_artist', 'db_genre', 'db_masterpiece', 'db_museum')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('db_artist', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('db_genre', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('db_masterpiece', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('db_museum', 200)
;

