package talkie.common.corba;


/**
* talkie/common/corba/_IDLTalkieServerImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 20:13:06 MSK
*/

public abstract class _IDLTalkieServerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements talkie.common.corba.IDLTalkieServer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _IDLTalkieServerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
    _methods.put ("postMessage", new java.lang.Integer (2));
    _methods.put ("whoIsHere", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/IDLTalkieServer/login
       {
         talkie.common.corba.IDLTalkieClient client = talkie.common.corba.IDLTalkieClientHelper.read (in);
         boolean $result = false;
         $result = this.login (client);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // corba/IDLTalkieServer/logout
       {
         String login = in.read_string ();
         this.logout (login);
         out = $rh.createReply();
         break;
       }

       case 2:  // corba/IDLTalkieServer/postMessage
       {
         String login = in.read_string ();
         String message = in.read_string ();
         this.postMessage (login, message);
         out = $rh.createReply();
         break;
       }

       case 3:  // corba/IDLTalkieServer/whoIsHere
       {
         String login = in.read_string ();
         this.whoIsHere (login);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/IDLTalkieServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _IDLTalkieServerImplBase
