package talkie.common.corba;


/**
* talkie/common/corba/IDLTalkieClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 20:22:16 MSK
*/

public interface IDLTalkieClientOperations 
{
  String getLogin ();
  String getPass ();
  void deliverMessage (String message);
} // interface IDLTalkieClientOperations
