package talkie.common.corba;

/**
* talkie/common/corba/IDLTalkieClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 20:22:16 MSK
*/

public final class IDLTalkieClientHolder implements org.omg.CORBA.portable.Streamable
{
  public talkie.common.corba.IDLTalkieClient value = null;

  public IDLTalkieClientHolder ()
  {
  }

  public IDLTalkieClientHolder (talkie.common.corba.IDLTalkieClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = talkie.common.corba.IDLTalkieClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    talkie.common.corba.IDLTalkieClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return talkie.common.corba.IDLTalkieClientHelper.type ();
  }

}
