package talkie.common.corba;


/**
* talkie/common/corba/IDLTalkieClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 20:13:06 MSK
*/

public interface IDLTalkieClient extends IDLTalkieClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDLTalkieClient
