package talkie.server.dispatchers.corba;


/**
* talkie/server/dispatchers/corba/IDLTalkieServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talkie.idl
* 12 Декабрь 2008 г. 16:29:52 MSK
*/

abstract public class IDLTalkieServerHelper
{
  private static String  _id = "IDL:corba/IDLTalkieServer:1.0";

  public static void insert (org.omg.CORBA.Any a, talkie.server.dispatchers.corba.IDLTalkieServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static talkie.server.dispatchers.corba.IDLTalkieServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (talkie.server.dispatchers.corba.IDLTalkieServerHelper.id (), "IDLTalkieServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static talkie.server.dispatchers.corba.IDLTalkieServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IDLTalkieServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, talkie.server.dispatchers.corba.IDLTalkieServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static talkie.server.dispatchers.corba.IDLTalkieServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof talkie.server.dispatchers.corba.IDLTalkieServer)
      return (talkie.server.dispatchers.corba.IDLTalkieServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      talkie.server.dispatchers.corba._IDLTalkieServerStub stub = new talkie.server.dispatchers.corba._IDLTalkieServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static talkie.server.dispatchers.corba.IDLTalkieServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof talkie.server.dispatchers.corba.IDLTalkieServer)
      return (talkie.server.dispatchers.corba.IDLTalkieServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      talkie.server.dispatchers.corba._IDLTalkieServerStub stub = new talkie.server.dispatchers.corba._IDLTalkieServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
