package ru.spb.etu.server.model.auto;

import java.util.List;

/** Class _DbArtist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DbArtist extends org.apache.cayenne.CayenneDataObject {

    public static final String BIRTHDATE_PROPERTY = "birthdate";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String IMAGE_URL_PROPERTY = "imageUrl";
    public static final String NAME_PROPERTY = "name";
    public static final String PICTURE_PROPERTY = "picture";
    public static final String ARTIST_MASTERPIECE_PROPERTY = "artistMasterpiece";
    public static final String ARTIST_PAINTINGS_PROPERTY = "artistPaintings";
    public static final String ARTIST_SCULPTURE_PROPERTY = "artistSculpture";

    public static final String ARTIST_ID_PK_COLUMN = "artistID";

    public void setBirthdate(java.util.Date birthdate) {
        writeProperty("birthdate", birthdate);
    }
    public java.util.Date getBirthdate() {
        return (java.util.Date)readProperty("birthdate");
    }
    
    
    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setImageUrl(String imageUrl) {
        writeProperty("imageUrl", imageUrl);
    }
    public String getImageUrl() {
        return (String)readProperty("imageUrl");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setPicture(byte[] picture) {
        writeProperty("picture", picture);
    }
    public byte[] getPicture() {
        return (byte[])readProperty("picture");
    }
    
    
    public void addToArtistMasterpiece(ru.spb.etu.server.model.DbMasterpiece obj) {
        addToManyTarget("artistMasterpiece", obj, true);
    }
    public void removeFromArtistMasterpiece(ru.spb.etu.server.model.DbMasterpiece obj) {
        removeToManyTarget("artistMasterpiece", obj, true);
    }
    public List getArtistMasterpiece() {
        return (List)readProperty("artistMasterpiece");
    }
    
    
    public void addToArtistPaintings(ru.spb.etu.server.model.DbPainting obj) {
        addToManyTarget("artistPaintings", obj, true);
    }
    public void removeFromArtistPaintings(ru.spb.etu.server.model.DbPainting obj) {
        removeToManyTarget("artistPaintings", obj, true);
    }
    public List getArtistPaintings() {
        return (List)readProperty("artistPaintings");
    }
    
    
    public void addToArtistSculpture(ru.spb.etu.server.model.DbSculpture obj) {
        addToManyTarget("artistSculpture", obj, true);
    }
    public void removeFromArtistSculpture(ru.spb.etu.server.model.DbSculpture obj) {
        removeToManyTarget("artistSculpture", obj, true);
    }
    public List getArtistSculpture() {
        return (List)readProperty("artistSculpture");
    }
    
    
}
