package ru.spb.etu.server.model.auto;

import java.util.List;

/** Class _DbMuseum was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DbMuseum extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String IMAGE_URL_PROPERTY = "imageURL";
    public static final String NAME_PROPERTY = "name";
    public static final String PICTURE_PROPERTY = "picture";
    public static final String WWW_PROPERTY = "www";
    public static final String MUSEUM_MASTERPIECE_PROPERTY = "museumMasterpiece";

    public static final String MUSEUM_ID_PK_COLUMN = "museumID";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setImageURL(String imageURL) {
        writeProperty("imageURL", imageURL);
    }
    public String getImageURL() {
        return (String)readProperty("imageURL");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setPicture(byte[] picture) {
        writeProperty("picture", picture);
    }
    public byte[] getPicture() {
        return (byte[])readProperty("picture");
    }
    
    
    public void setWww(String www) {
        writeProperty("www", www);
    }
    public String getWww() {
        return (String)readProperty("www");
    }
    
    
    public void addToMuseumMasterpiece(ru.spb.etu.server.model.DbMasterpiece obj) {
        addToManyTarget("museumMasterpiece", obj, true);
    }
    public void removeFromMuseumMasterpiece(ru.spb.etu.server.model.DbMasterpiece obj) {
        removeToManyTarget("museumMasterpiece", obj, true);
    }
    public List getMuseumMasterpiece() {
        return (List)readProperty("museumMasterpiece");
    }
    
    
}
