package ru.spb.etu.server.model.auto;

/** Class _DbMasterpiece was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DbMasterpiece extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATION_YEAR_PROPERTY = "creationYear";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_TYPE_PROPERTY = "idType";
    public static final String IMAGE_URL_PROPERTY = "imageURL";
    public static final String PHOTO_PROPERTY = "photo";
    public static final String TITLE_PROPERTY = "title";
    public static final String ISPAINTING_PROPERTY = "ispainting";
    public static final String ISSCULPTURE_PROPERTY = "issculpture";
    public static final String MYARTIST_PROPERTY = "myartist";
    public static final String MYGENRE_PROPERTY = "mygenre";
    public static final String MYMUSEUM_PROPERTY = "mymuseum";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreationYear(Integer creationYear) {
        writeProperty("creationYear", creationYear);
    }
    public Integer getCreationYear() {
        return (Integer)readProperty("creationYear");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setIdType(Integer idType) {
        writeProperty("idType", idType);
    }
    public Integer getIdType() {
        return (Integer)readProperty("idType");
    }
    
    
    public void setImageURL(String imageURL) {
        writeProperty("imageURL", imageURL);
    }
    public String getImageURL() {
        return (String)readProperty("imageURL");
    }
    
    
    public void setPhoto(String photo) {
        writeProperty("photo", photo);
    }
    public String getPhoto() {
        return (String)readProperty("photo");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setIspainting(ru.spb.etu.server.model.DbPainting ispainting) {
        setToOneTarget("ispainting", ispainting, true);
    }

    public ru.spb.etu.server.model.DbPainting getIspainting() {
        return (ru.spb.etu.server.model.DbPainting)readProperty("ispainting");
    } 
    
    
    public void setIssculpture(ru.spb.etu.server.model.DbSculpture issculpture) {
        setToOneTarget("issculpture", issculpture, true);
    }

    public ru.spb.etu.server.model.DbSculpture getIssculpture() {
        return (ru.spb.etu.server.model.DbSculpture)readProperty("issculpture");
    } 
    
    
    public void setMyartist(ru.spb.etu.server.model.DbArtist myartist) {
        setToOneTarget("myartist", myartist, true);
    }

    public ru.spb.etu.server.model.DbArtist getMyartist() {
        return (ru.spb.etu.server.model.DbArtist)readProperty("myartist");
    } 
    
    
    public void setMygenre(ru.spb.etu.server.model.DbGenre mygenre) {
        setToOneTarget("mygenre", mygenre, true);
    }

    public ru.spb.etu.server.model.DbGenre getMygenre() {
        return (ru.spb.etu.server.model.DbGenre)readProperty("mygenre");
    } 
    
    
    public void setMymuseum(ru.spb.etu.server.model.DbMuseum mymuseum) {
        setToOneTarget("mymuseum", mymuseum, true);
    }

    public ru.spb.etu.server.model.DbMuseum getMymuseum() {
        return (ru.spb.etu.server.model.DbMuseum)readProperty("mymuseum");
    } 
    
    
}
