module corba {
    interface IDLTalkieServer {
        boolean login(in string login, in string pass);
        void logout(in string login);
        void postMessage(in string login, in string message);
        void whoIsHere(in string login);
    };
};