package ru.spb.etu.server.model.auto;

import java.util.List;

/** Class _DbArtist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DbArtist extends org.apache.cayenne.CayenneDataObject {

    public static final String BIRTHDATE_PROPERTY = "birthdate";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String IMAGE_URL_PROPERTY = "imageUrl";
    public static final String NAME_PROPERTY = "name";
    public static final String MASTERPIECES_PROPERTY = "masterpieces";

    public static final String ID_PK_COLUMN = "ID";

    public void setBirthdate(java.util.Date birthdate) {
        writeProperty("birthdate", birthdate);
    }
    public java.util.Date getBirthdate() {
        return (java.util.Date)readProperty("birthdate");
    }
    
    
    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setImageUrl(String imageUrl) {
        writeProperty("imageUrl", imageUrl);
    }
    public String getImageUrl() {
        return (String)readProperty("imageUrl");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToMasterpieces(ru.spb.etu.server.model.DbMasterpiece obj) {
        addToManyTarget("masterpieces", obj, true);
    }
    public void removeFromMasterpieces(ru.spb.etu.server.model.DbMasterpiece obj) {
        removeToManyTarget("masterpieces", obj, true);
    }
    public List getMasterpieces() {
        return (List)readProperty("masterpieces");
    }
    
    
}
